### ISSUE TITLE
模型大小能再小一点吗？

### ISSUE THREAD

**Issue by mr-bogey** [ZJFERAL/APaddleOCR#1]
模型大小能再小一点吗？
我之前使用的是v2版本的模型，它们加起来只有4M，但是看你这个项目内的模型，大小加起来快16M了。有什么方法能把模型体积降下来吗？

**Comment by ZJFERAL** [comment]
根据官方模型转化的，体积压缩这方面没有研究，可以尝试自己打包一下 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/lite/readme.md

**Comment by mr-bogey** [comment]
好的，谢谢
